version: '3'
services:
  app:
    container_name: express-template
    build: .
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
  db:
    container_name: express-template-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
