swagger: "2.0"
info:
  description: "This is a sample swagger document."
  version: "1.0.0"
  title: "Swagger Template"
  contact:
    email: "anatoool@yandex.ru"

schemes:
  - http
  - https

securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header

paths:
  /ideas:
    get:
      security:
        - JWT: []