swagger: "2.0"
info:
  description: "This is a sample swagger document."
  version: "1.0.0"
  title: "Swagger Template"
  contact:
    email: "anatoool@yandex.ru"

basePath: /api

schemes:
  - http
  - https

securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      petId:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
        format: "int32"
      shipDate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "placed"
        - "approved"
        - "delivered"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Order"